version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/.github"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directories:
  - /containers/*
  schedule:
    interval: "weekly"
